# Generated by Django 3.1.5 on 2021-01-10 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='姓名')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女')], default='male', max_length=30, verbose_name='性别')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='课程名')),
                ('scores', models.IntegerField(verbose_name='分数')),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='apps.student')),
            ],
        ),
    ]
